#!/bin/bash

echo "Verifies contents of hosts generated by Ansible playbooks"

echo '=================================================================='
ansible all -a "cat /etc/machine-id"
echo '=================================================================='
ansible all -a "hostname -f"
echo '=================================================================='
ansible all -a "cat /etc/hosts"

echo '=================================================================='
echo "KUBERNETES.LIST"
ansible all -a "cat /etc/apt/sources.list.d/kubernetes.list"

echo '=================================================================='
echo "KUBERNETES.CONF"
ansible all -a "cat /etc/sysctl.d/kubernetes.conf"

echo '=================================================================='
echo "KERNEL MODS. If below are empty, then they are not installed"
ansible all -a "sudo lsmod"

echo '=================================================================='
echo "CONTAINERD SERVICE. Should be running"
ansible all -a "sudo systemctl status containerd"

echo '=================================================================='
echo "SWAP. If below is empty, then swap is disabled as it should be"
ansible all -a "sudo swapon --show"


echo '=================================================================='
echo 'KUBELET: Status and enabled'
ansible master -a "sudo systemctl status kubelet"
ansible master -a "sudo systemctl is-enabled kubelet"

